title: About the Foundation for Public Code
permalinks: pretty
markdown: kramdown

include:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
remote_theme: publiccodenet/jekyll-theme

# Exclude the `vendor` folder created by Travis
exclude:
  - vendor

# Display Table of Contents on every page, disable by adding `toc: false` to the front matter of any file
toc: true

# show_navigation: true
show_breadcrumbs: true

# Display the headings separately
titles_from_headings:
  strip_title: true
